### ISSUE TITLE
HL7 Multipara Monitor Integration V2

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#694]
Integrate with Multipara Monitors to receive Vitals of Patients with Time Series Data Stored to Care

- [ ] Setup Redis in Middleware to store HL7 Data coronasafe/teleicu_middleware#31
- [ ] Authentication for Assets #677 
- [ ] OIDC Server for Middleware Server coronasafe/teleicu_middleware#25
- [ ] Daily Rounds API for Middleware #671 
- [ ] CRON Job to Sync Data to Care #coronasafe/teleicu_middleware#32
