### ISSUE TITLE
HL7 Multipara Monitor Integration POC

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#695]
Upgrade Care to integrate with HL7 Multipara Monitors
- [x] Create AssetIntegration Classes to Support integration of different Types of Assets #651
- [x] Middleware API to receive data from HL7 Adapter coronasafe/teleicu_middleware#14
- [x] Middleware API to fetch data for a certain bed coronasafe/teleicu_middleware#33
- [x] Build Patient Hub View to show Live Data from Asset coronasafe/care_fe#2108
