### ISSUE TITLE
Upgrade Camera Integration; Improve Latency

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#702]
The Camera Integration currently use the HLS (HTTP Live Streaming) protocol. We have identified MSE (Media Source Extensions) as a viable alternative. The lack of good MSE Servers and React-based MSE Players is the challenge here

- [x] coronasafe/care_fe#2154
- [x] coronasafe/teleicu_middleware#35
- [ ] coronasafe/care#713
- [ ] coronasafe/care#704
- [x] coronasafe/teleicu_middleware#36
- [x] Integration and Deployment
